### ISSUE TITLE
question about example run on 1.28?

### ISSUE THREAD

**Issue by jimiatworking** [htammen/SmartTableExample#1]
Hi, I have a question about could this example run on SAPUI5 1.28? I'm trying to search on google and try to run on v1.28 enviroment, but no luck. Is there any limitation on smarttable UI5 version?

**Comment by htammen** [comment]
Just look at the API documentation. There you see that some functions are already available from 1.26 on. I used it in a project with 1.28
https://sapui5.hana.ondemand.com/sdk#/api/sap.ui.comp.smarttable.SmartTable/overview
